<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Hàng hóa-Thêm mới hàng hóa</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>8d63e7ef-efb5-4455-84b3-bf4f8ece8e63</testSuiteGuid>
   <testCaseLink>
      <guid>e391c0a9-bbf4-4f5b-94ac-9dd84c38d625</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Quản lý hàng hóa/ThemMoi/Func_HH42-Thêm mới sản phẩm thành công</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>141cf003-f487-4af6-9961-1f554aee1b55</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db4e549c-6182-4a30-a6f1-ababfce61856</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b76e2fd1-58b2-4010-ac2d-d5ecd09e9aab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c9f4050f-37b9-4b71-ad1f-96d0e7d01fc7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba127cea-25fe-4274-927a-9cb52f3b07c0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c08d009b-59e5-45a4-84ec-6bef13044aa8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c8b649c8-0c1e-48b6-bb80-e280021c5ed0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Quản lý hàng hóa/ThemMoi/Func_HH43- Thêm mới sp với loại Dịch vụ</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>b5e370f5-5eda-48a6-83ee-d68cee4d127d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Quản lý hàng hóa/ThemMoi/Func_HH44- Thêm mới sp với loại Hàng hóa</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>83651cfb-db61-47fc-9a11-da8ed0f37edf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Quản lý hàng hóa/ThemMoi/Func_HH45- Thêm mới sp với loại Combo</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>3739992c-27b1-4388-b061-198626201161</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Quản lý hàng hóa/ThemMoi/Func_HH46---Func_HH49-Thêm mới sản phẩm với các nhóm hàng</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>756cb6a1-6e3e-48f0-a784-011bb7346692</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Product/NhomLoaiHang</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f8a15b15-0483-45f6-85ea-c0acf66e88a4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>756cb6a1-6e3e-48f0-a784-011bb7346692</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Nhóm</value>
         <variableId>c429e8c5-01a9-4887-be08-cff608a2c846</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f75553c3-eeeb-4e4b-9cf4-279e84eed349</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Quản lý hàng hóa/ThemMoi/Func_HH50- Thêm mới sản phẩm với hình ảnh</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf4fd8db-eacb-4d31-b2aa-499f37364dca</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>683164e7-1b21-4018-a54f-e7b157aa1738</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Quản lý hàng hóa/ThemMoi/Func_HH51- Kiểm tra tự sinh mã hàng</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d64347f4-dbcc-40c3-9abc-968253368609</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>029c77fd-d242-48bf-9b12-78821054a2e2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>00bd8229-7516-4792-926e-7d8c290ae9b4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>999c9acc-530d-4eca-b020-7db056f6510a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b50e9b86-94ff-456b-8625-1c5fe52b6964</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8bd75475-8827-43bb-be9f-16b9a985a949</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ee465369-866b-444b-af0f-514109af89c6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Quản lý hàng hóa/ThemMoi/Func_HH52_Kiểm tra bỏ trống trường bắt buộc</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>87c72a68-e00a-4b28-b24b-4bb7acfccd94</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b38b854b-3aa9-48cf-9551-4d6883672cfb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>67cc6f0a-db35-44cd-985a-27929d2b65ff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ccf84d8a-de6e-4758-9c81-3dfa810fa8c6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aeac1166-dd34-41e4-8b07-95d5329f788e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3608398c-be73-4032-b460-856f32b03249</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6332a5cd-dadb-4d28-a4bc-e6b858064962</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Quản lý hàng hóa/ThemMoi/Func_HH54--59- Kiểm tra không điền đầy đủ thông tin</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>0b725e73-5419-42e4-8fe3-fcd3d7e63f3b</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Product/BoTrongCacTruong</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1147060b-13c8-4892-9d5f-4e48c1496c0a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0b725e73-5419-42e4-8fe3-fcd3d7e63f3b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>giaBan</value>
         <variableId>5207376f-4d7e-47fc-a54b-3742ddd2befb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0b725e73-5419-42e4-8fe3-fcd3d7e63f3b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>giaVon</value>
         <variableId>76136b9d-b26c-4497-8d95-db35c196ae12</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0b725e73-5419-42e4-8fe3-fcd3d7e63f3b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>tonKho</value>
         <variableId>0c977b40-4eb4-420c-893a-6f2c4b633167</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0b725e73-5419-42e4-8fe3-fcd3d7e63f3b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>dvt</value>
         <variableId>98465b47-f1ae-4172-a113-db57a9436b5c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0b725e73-5419-42e4-8fe3-fcd3d7e63f3b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>tc_id</value>
         <variableId>ce7d974d-a960-44fc-a76e-8b31e87b1f3c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>32850712-8d86-4687-9dff-5ab319a2f6eb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Quản lý hàng hóa/ThemMoi/Func_HH60--Kiểm tra khi click Thoát</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c107d77c-8685-4fe2-8139-cb52685fa5d9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>55a14abe-6b55-4827-bb6e-0bf8f310d088</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88d128cf-0504-4b08-bcb5-cee428474361</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ffbecc0-3a4b-42e2-9fd3-48225b69bd49</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>70c78448-d7df-402f-a425-d6f1b7fbbdc5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>246a61c2-4d3a-4dc4-a821-7d9ebd93fd25</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>05a8cb88-910a-42f3-a14c-5b8eebee5c96</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Quản lý hàng hóa/ThemMoi/Func_HH61-Kiểm tra thêm mới với button Lưu và Thêm Mới</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa4cc6b5-9328-4f63-a078-69ec16490ff5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ceb2a7b-b6e0-4644-8622-d6e96177bddc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7aba7aa5-5c46-4407-a9a2-d821e365c49b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0e45070-028a-4e2e-ac3b-2ff66b676238</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02c82fa9-c619-43a9-9917-1a0599e13f64</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1c71243b-bd93-4a44-b500-163150fc740e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f5ea40f2-5f3c-4e16-9911-84a2f5d0fd89</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fb3f193b-7abc-4cdc-91c9-f709390ed078</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Quản lý hàng hóa/ThemMoi/Func_HH62-Kiểm tra thêm mới với button Lưu và Copy</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bdabeb22-e7cd-4089-aa8d-ba6a876f2b00</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1c25c601-8272-4ab5-bef4-443ae5b7b863</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c754ca7f-9d92-4132-b8a0-8c7c70ee303f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a87de7b-741f-4301-aa1c-a6b3d8b145f3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bcdd8597-cd2e-4b65-b05d-af9244a0788e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>696b4abd-402c-422d-b4ad-9eed930eb145</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>074b1a08-7598-44c3-bfd1-a60c1ce158e6</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
