<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Hàng hóa- Sửa hàng hóa</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>ae40caa8-a708-48f0-9670-4aec46cfcc02</testSuiteGuid>
   <testCaseLink>
      <guid>b82d5ddb-0354-453d-bca6-cd14fd7edd0f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Quản lý hàng hóa/Sua/Func_HH62 - Sửa thành công hàng hóa</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dd6fd73c-5609-4457-bc48-8337988987d1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a26eaf7-4933-411a-9de9-1d89c34b910c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8786bbcd-43ca-4d31-acaf-a4de4f30719d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35468f39-0e53-403f-89c1-89c2b4c206b6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40e5a31d-ef86-44d3-adad-c9cc1829f99a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2357b9ae-32bd-43d5-93a9-3cac889d8c33</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1898716f-a056-477f-acaf-349bd8ed5557</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Quản lý hàng hóa/Sua/Func_HH63- Sửa bỏ trống trường bắt buộc</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>492cc16b-cd83-4ff7-b773-c06c08dddd86</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d6ab5d7-5605-413e-805d-c4a851cb1ad8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2a0ca621-437f-4607-b7ee-a52a36bbde75</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>42488464-a5fe-4c45-a3ea-90b348c5949b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d364b62-331e-4cb3-8155-d34bb29d3adb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fe9a6736-5ee9-458b-ba9e-2eede2b1914b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3512cda1-68de-4451-b273-297eab3c6e8c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Quản lý hàng hóa/Sua/Func_HH64 - Sửa thành mã trùng</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05a9147c-13ef-48f9-879d-8dfac6471223</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>455fed7b-df30-4fde-a02f-0f69ce7fc0f9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0c0a939-1d91-42f3-ae13-9b2aa3da159a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e9ad4c3e-c764-4d0a-b8fe-e0d77db1da18</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e662866-098a-4ece-b9bf-fe8e8ab30a5f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a2f06a76-0394-47f7-b2dd-a216f0078cbe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d1e6469-f95d-48de-b06c-912c766eb9b1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7ee7ae3b-066b-46f1-a600-1d7de683dc3d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Quản lý hàng hóa/Sua/Func_HH65- Sửa và Thoát</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a6daf19-a252-49a6-bfa3-3924eb316a2f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>28cd94b4-5dd4-4cfa-91bc-4e6b2948152d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d8f62539-c748-4f94-9aa6-6ea4f8c507e2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1751d6e7-d9b7-4e09-91b2-cef7ffb164dd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>afdb3d1d-b21c-4949-b6c0-f0f462c544e3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a286d44-d3fb-403b-b0f5-3c0ac13bdeab</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5a8549dd-fcb8-4c1b-b161-8928bc5f5791</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Quản lý hàng hóa/Sua/Func_HH66- Sửa và Thêm Mới</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>ffc16e58-8dd4-4aa7-ad3e-fe85e9763afb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Quản lý hàng hóa/Sua/Func_HH67-Sửa và Copy</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfc89925-8b9a-473e-ad9d-b222b34586ff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7bf06df2-27f7-4f03-8f54-1b486904b8b9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a285a96-e7dd-4dee-b637-1b46895608a1</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
