<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>NhapHang_TimKiemPhieuNhap</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>c0755436-9afa-43fc-9f41-1b3b960726cd</testSuiteGuid>
   <testCaseLink>
      <guid>e98e026f-d2d0-4bd7-a7e1-cb77b6a980a5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nhập Hàng/TimKiem/Func_NH01 - Tìm kiếm theo Mã CT có tồn tại</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a02430ca-2d74-4935-bd04-798be3e147d7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c9c214e0-9525-445e-9aa2-034960651bd7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nhập Hàng/TimKiem/Func_NH02- Tìm kiếm theo Mã CT không tồn tại</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>119b5f08-2464-40b3-829c-c6be219630b2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1ed943a0-22b9-4d20-b27c-c30b3481008b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nhập Hàng/TimKiem/Func_NH03 - Tìm kiếm theo mã hàng hóa có tồn tại</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8cbcf743-9398-4e13-8d67-0af61c74af94</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>66e29d69-c941-485e-a9c4-9803ea2536d6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nhập Hàng/TimKiem/Func_NH04 - Tìm kiếm theo mã nhà cung cấp</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3eb13675-31b2-47ee-9abe-33733fb4ca2b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>61266942-2f29-4ade-94d5-4be8a1d9df64</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ac38a556-9372-4efa-86db-46d65ae6f944</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nhập Hàng/TimKiem/Func_NH05- Tìm kiếm theo trạng thái hoàn thành</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0de4db70-1df9-47f6-b0a7-fb8a244e905e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db138e4f-fe8e-4f74-b4e4-1129298af1dd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>638f3218-8984-498e-add8-89364712fb0e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nhập Hàng/TimKiem/Func_NH06- Tìm kiếm theo trạng thái Hủy</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e49116e-77e5-4d0f-9406-444e4dae7d86</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ead8a63a-85c9-4fec-81d1-9486cd93640e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1c2c9b25-5a76-49e7-b207-8ba0f0e5f623</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nhập Hàng/TimKiem/Func_NH07- Tìm kiếm theo trạng thái Đang xử lý</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>195dac77-acfd-4cfd-8f74-4d45ba3b502f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7b886bcc-f995-4628-9761-de5723cd4356</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>27e6c695-c5e5-474d-ad39-67b0f898a0c9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nhập Hàng/TimKiem/Func_NH08- Tìm kiếm theo thời gian Hôm nay</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>5410a009-0128-4cf5-b64c-f1c2bcde08f3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nhập Hàng/TimKiem/Func_NH09- Tìm kiếm theo Thời gian Tháng này</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>df89be2e-93c2-4e83-99f1-04c013207a3c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nhập Hàng/TimKiem/Func_NH10- Tìm kiếm theo thời gian Tháng trước</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
