<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>NhapHang_ThemMoiPhieuNhap</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>4290daf0-0a09-4ba2-8779-12eb369e06e1</testSuiteGuid>
   <testCaseLink>
      <guid>18cd3a12-f5ce-46ba-a9eb-f1d051d13bc9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nhập Hàng/ThemMoi/Func_NH11 -Nhập 1 hàng hóa thành công</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>7163706b-4ca3-4665-88b7-534f19d1dddb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nhập Hàng/ThemMoi/Func_NH12 -Nhập nhiều hàng hóa thành công</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>607e39d4-f77b-4321-aafe-c0e7739e99bd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nhập Hàng/ThemMoi/Func_NH13 - Nhập Hàng có chiết khấu</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ab41744-ce44-42fb-a93b-6c1587a9b74b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4ed9e3de-3e0f-4bcd-8a6a-f9195dd40668</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nhập Hàng/ThemMoi/Func_NH14 - Nhập hàng với Nhà cung cấp</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5406fe07-c3ad-4286-9ec6-bd1a2dfa86ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3858e18c-df3f-4707-89bc-f3fd41f5bd50</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a105d648-f0d4-482b-937e-e9a99d220e11</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nhập Hàng/ThemMoi/Func_NH15- Nhập hàng với trạng thái đang xử lý</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>21ef95aa-fedf-45cb-9a9e-8d9cb5b94652</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c403d3ac-89c1-4cfb-9ecf-1f1e1a1f767a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f925fd2b-f00a-4239-b22b-a6c828da509e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6442d19a-8d55-4b1b-837e-ffe4abfdf997</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nhập Hàng/ThemMoi/Func_NH16- Nhập hàng với trạng thái hoàn thành</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac0b2d9f-ea10-4e79-bdeb-6bcc7a6bc926</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>63830253-1881-437e-b693-18e742a8956c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a99d8f6b-5f2f-4349-8b5f-e01462d932d8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d2d8e2c3-9b62-42d0-82d1-dc015136e87b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nhập Hàng/ThemMoi/Func_NH17- Nhập hàng với ngày nhập</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad2baf24-1e70-43f3-80ef-1020d5c9a42f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ee3aba1-006b-4a8a-96fc-fe9b8a1b4f9c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>989da0dd-b050-4d04-89ff-3908c17ba821</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>92cad186-16e5-4e78-ac39-ef6eefa0be97</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nhập Hàng/ThemMoi/Func_NH18- Nhập hàng với người tạo</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0966786b-6d50-40ac-af5f-2ebeacc75bbf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d5950d1-8648-4fff-963e-5ad19af4b3a8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>12583c33-0a5f-48b6-b8eb-0df8de46af6f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8319fff6-e976-4a9c-ba31-1aaca0a035dc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nhập Hàng/ThemMoi/Func_NH19- Thêm mới verify từng dòng hàng hóa</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23ff73a5-144b-4dc4-b33c-0d516d69b7af</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab540b9a-ffa4-401c-91d7-4239c6ad2380</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4dabaa09-ed95-4e17-9b1b-1f3eb6e04879</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bd10cd42-62cf-48bc-be42-4999fab7c2e4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nhập Hàng/ThemMoi/Func_NH20- Thêm mới đầy đủ các thông tin</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88e4edf4-cdd5-469e-bf0c-a7004fea062d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>873e3d68-e06c-48b0-bd54-706a24cdba56</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>090aa4ed-0704-488f-84f5-7148459f1e56</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>aac706a0-6765-4ac2-a8c3-dc4cdbd8024e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nhập Hàng/ThemMoi/Func_NH21- Nhập hàng và ấn Thoát</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>ab9f3990-c178-4591-b87e-ee059fbb1cc3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nhập Hàng/ThemMoi/Func_NH22 - Nhập hàng với mã CT đã tồn tại</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>21abf500-4128-437c-a414-cd09ca1410be</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nhập Hàng/ThemMoi/Func_NH23 - Nhập hàng với không đủ thông tin bắt buộc</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>126622ec-45b1-4c73-b7a5-3bd7049d74ce</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nhập Hàng/ThemMoi/Func_NH24- Kiểm tra tăng tồn kho</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
