<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Validate_TimKiem</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>66d6f7cb-538d-42f2-9413-d7e21323122f</testSuiteGuid>
   <testCaseLink>
      <guid>b2d179ad-8595-4a44-9abf-e05fc92e6f2b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/common/login</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>71d7a942-c5f1-4123-997f-c7024c5ca6ac</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Quản lý hàng hóa/Validate/Val_HH01--11 - Validate Tìm kiếm</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>a155718e-cb38-4a80-bb13-e95db2eefdc9</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Product/ValidateTimKiem</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>a155718e-cb38-4a80-bb13-e95db2eefdc9</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>ten</value>
         <variableId>3a68b397-f56f-4845-ac25-0aa0192fc772</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>a155718e-cb38-4a80-bb13-e95db2eefdc9</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>NCC</value>
         <variableId>f39ccd8b-a6be-4ec8-ac89-19b367ffb096</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>a155718e-cb38-4a80-bb13-e95db2eefdc9</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>type</value>
         <variableId>049ce0a9-461e-4905-92e9-69281257caf8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>a155718e-cb38-4a80-bb13-e95db2eefdc9</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TC_id</value>
         <variableId>51fca12a-724a-414c-8694-4dab19b0b765</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
