<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tit_ManCapNhat</name>
   <tag></tag>
   <elementGuidId>3be2e9c3-0040-437e-8c8b-245dfdc0263e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//h1[@ng-bind=&quot;$root.title&quot;])[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
