<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DangNhap_Funtion</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>158b424b-1b8a-471d-850b-d30f16878c0a</testSuiteGuid>
   <testCaseLink>
      <guid>d3fb0e34-45d1-4c82-9473-aade411fcc7b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Đăng nhập/TC_Fun_DN01___Fun_DN07</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>c082f13e-eccb-42bc-b49a-6a3a23b73985</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Login/loginFuntion</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>c082f13e-eccb-42bc-b49a-6a3a23b73985</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>c9d74298-a1da-4276-ae0e-00567f516b16</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>c082f13e-eccb-42bc-b49a-6a3a23b73985</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>baef0906-f1c3-4a6e-abe1-83aeca1f4deb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>c082f13e-eccb-42bc-b49a-6a3a23b73985</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>LoginType</value>
         <variableId>da2207be-2223-4c16-83c4-afbb4ea0ab35</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>c082f13e-eccb-42bc-b49a-6a3a23b73985</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>expected</value>
         <variableId>42b0b388-2df0-40fc-a64c-fae5be17b1b0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>c082f13e-eccb-42bc-b49a-6a3a23b73985</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>expectedMessage</value>
         <variableId>2d3391fd-fcd9-44ef-ab8f-8c2c4d49dcc4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>c082f13e-eccb-42bc-b49a-6a3a23b73985</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TC_id</value>
         <variableId>13496545-e302-47bd-adc0-c6208bcfe665</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2cf19ed9-3499-43de-a464-c9ae65f3856a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Đăng nhập/TC_Func_DN08- Đăng nhập với vai trò admin</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e3d13315-8e88-401c-9277-47b59e4237f7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ed595e12-9020-4870-9d3f-238b4d78113c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d21e663d-d18f-48ba-adad-9e258ad65eb2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>25f25080-d55e-47e6-804f-760c67fd3351</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Đăng nhập/TC_Func_DN09- Đăng nhập với vai trò nhân viên được phân quyền</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>799da99e-22c2-4220-a772-ef1f5755d165</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db98d4ab-5a52-48de-9764-a61cb6045cec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>68d88761-eb30-458a-8435-c9d63b52a4bc</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
