<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Nhập hàng - Tìm kiếm</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>05e94e1f-d2e6-4cca-90c1-eede330acb11</testSuiteGuid>
   <testCaseLink>
      <guid>327647c5-512e-43ba-be25-1ab5641783a0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nhập Hàng/TimKiem/Func_NH01 - Tìm kiếm theo Mã CT có tồn tại</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a02430ca-2d74-4935-bd04-798be3e147d7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e66876ab-dc77-4cc3-84c5-751cca3b282b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nhập Hàng/TimKiem/Func_NH02- Tìm kiếm theo Mã CT không tồn tại</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>119b5f08-2464-40b3-829c-c6be219630b2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d9a21080-92f7-41ed-8199-855c917092bf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nhập Hàng/TimKiem/Func_NH03 - Tìm kiếm theo mã hàng hóa có tồn tại</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8cbcf743-9398-4e13-8d67-0af61c74af94</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>beafc6e7-b1a7-4b4e-8a10-f5ac819bc6e5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nhập Hàng/TimKiem/Func_NH04 - Tìm kiếm theo mã nhà cung cấp</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3eb13675-31b2-47ee-9abe-33733fb4ca2b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>61266942-2f29-4ade-94d5-4be8a1d9df64</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>42b5a638-0295-4a81-9bf4-b851568e6576</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nhập Hàng/TimKiem/Func_NH05- Tìm kiếm theo trạng thái hoàn thành</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0de4db70-1df9-47f6-b0a7-fb8a244e905e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db138e4f-fe8e-4f74-b4e4-1129298af1dd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4a06a7da-7ba1-43f0-9a98-d6fb74b619c3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nhập Hàng/TimKiem/Func_NH06- Tìm kiếm theo trạng thái Hủy</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e49116e-77e5-4d0f-9406-444e4dae7d86</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ead8a63a-85c9-4fec-81d1-9486cd93640e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>93048ca9-0e0a-4160-9161-e05c20fc3db1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nhập Hàng/TimKiem/Func_NH07- Tìm kiếm theo trạng thái Đang xử lý</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>195dac77-acfd-4cfd-8f74-4d45ba3b502f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7b886bcc-f995-4628-9761-de5723cd4356</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>78e80b51-43d1-4a31-9b48-d59c7269e4da</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nhập Hàng/TimKiem/Func_NH08- Tìm kiếm theo thời gian Hôm nay</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>321fa1c7-116b-4d36-8811-c242fe9c458e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nhập Hàng/TimKiem/Func_NH09- Tìm kiếm theo Thời gian Tháng này</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>b9a2b86d-1904-4b89-93ab-d96e71ed2b0b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nhập Hàng/TimKiem/Func_NH10- Tìm kiếm theo thời gian Tháng trước</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
