<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Nhập hàng _ Thêm phiếu nhập</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>463f386a-8f3a-4f5d-beff-947e790d6a13</testSuiteGuid>
   <testCaseLink>
      <guid>ab183a8a-b911-4cbd-ae04-147c1057d842</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nhập Hàng/ThemMoi/Func_NH11 -Nhập 1 hàng hóa thành công</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>a3c799a2-1265-45e5-9212-570ffbb9fa40</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nhập Hàng/ThemMoi/Func_NH12 -Nhập nhiều hàng hóa thành công</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>1e0c2fdc-6cce-46d5-aef0-925d490cfe84</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nhập Hàng/ThemMoi/Func_NH13 - Nhập Hàng có chiết khấu</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ab41744-ce44-42fb-a93b-6c1587a9b74b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6f893ba0-26f1-49c3-83ae-47acfb2911fd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nhập Hàng/ThemMoi/Func_NH14 - Nhập hàng với Nhà cung cấp</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5406fe07-c3ad-4286-9ec6-bd1a2dfa86ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3858e18c-df3f-4707-89bc-f3fd41f5bd50</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4dd54285-0aa5-45b3-b927-df4342fc5864</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nhập Hàng/ThemMoi/Func_NH15- Nhập hàng với trạng thái đang xử lý</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>21ef95aa-fedf-45cb-9a9e-8d9cb5b94652</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c403d3ac-89c1-4cfb-9ecf-1f1e1a1f767a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f925fd2b-f00a-4239-b22b-a6c828da509e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>eedc888f-3343-4f24-b73e-fd87d8bd3943</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nhập Hàng/ThemMoi/Func_NH16- Nhập hàng với trạng thái hoàn thành</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac0b2d9f-ea10-4e79-bdeb-6bcc7a6bc926</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>63830253-1881-437e-b693-18e742a8956c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a99d8f6b-5f2f-4349-8b5f-e01462d932d8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a3042dcb-2831-4200-af7c-431517d562c2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nhập Hàng/ThemMoi/Func_NH17- Nhập hàng với ngày nhập</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad2baf24-1e70-43f3-80ef-1020d5c9a42f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ee3aba1-006b-4a8a-96fc-fe9b8a1b4f9c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>989da0dd-b050-4d04-89ff-3908c17ba821</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b29973a6-bb3f-402a-b5a9-60daa48b5b72</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nhập Hàng/ThemMoi/Func_NH18- Nhập hàng với người tạo</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0966786b-6d50-40ac-af5f-2ebeacc75bbf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d5950d1-8648-4fff-963e-5ad19af4b3a8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>12583c33-0a5f-48b6-b8eb-0df8de46af6f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0902b760-b62f-4f91-862d-06cf687064a1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nhập Hàng/ThemMoi/Func_NH19- Thêm mới verify từng dòng hàng hóa</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23ff73a5-144b-4dc4-b33c-0d516d69b7af</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab540b9a-ffa4-401c-91d7-4239c6ad2380</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4dabaa09-ed95-4e17-9b1b-1f3eb6e04879</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cf6e3531-cd26-4535-82ef-213994d42bbc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nhập Hàng/ThemMoi/Func_NH20- Thêm mới đầy đủ các thông tin</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88e4edf4-cdd5-469e-bf0c-a7004fea062d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>873e3d68-e06c-48b0-bd54-706a24cdba56</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>090aa4ed-0704-488f-84f5-7148459f1e56</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>35fc21af-b6fc-4ae8-b4bc-af932dd93080</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nhập Hàng/ThemMoi/Func_NH21- Nhập hàng và ấn Thoát</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>ddd2dd3f-8103-45b4-a0c1-fef0f94c8598</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nhập Hàng/ThemMoi/Func_NH22 - Nhập hàng với mã CT đã tồn tại</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>a9713584-33de-4bfa-8b91-9c1c559924ef</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nhập Hàng/ThemMoi/Func_NH23 - Nhập hàng với không đủ thông tin bắt buộc</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>089709c6-32c9-4eb2-b894-7bc1a09aa08c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nhập Hàng/ThemMoi/Func_NH24- Kiểm tra tăng tồn kho</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
