<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TimKiem</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>592f6bc7-0f9a-4b49-ae50-7dd9ac556b75</testSuiteGuid>
   <testCaseLink>
      <guid>dca46aaa-e71f-4ba9-9c3a-3b472d57332a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nhập Hàng/TimKiem/Func_NH01 - Tìm kiếm theo Mã CT có tồn tại</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a02430ca-2d74-4935-bd04-798be3e147d7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ef435818-8f0b-4b62-b7c3-fc6608d75fe8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nhập Hàng/TimKiem/Func_NH02- Tìm kiếm theo Mã CT không tồn tại</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>119b5f08-2464-40b3-829c-c6be219630b2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d268964d-58ed-4b2f-97af-3db3aca60da0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nhập Hàng/TimKiem/Func_NH03 - Tìm kiếm theo mã hàng hóa có tồn tại</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8cbcf743-9398-4e13-8d67-0af61c74af94</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>666359f5-4f7f-4bb7-afeb-e0930ef04c74</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nhập Hàng/TimKiem/Func_NH04 - Tìm kiếm theo mã nhà cung cấp</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3eb13675-31b2-47ee-9abe-33733fb4ca2b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>61266942-2f29-4ade-94d5-4be8a1d9df64</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>904c7845-1d82-4027-8cf0-96dde81d8466</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nhập Hàng/TimKiem/Func_NH05- Tìm kiếm theo trạng thái hoàn thành</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0de4db70-1df9-47f6-b0a7-fb8a244e905e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db138e4f-fe8e-4f74-b4e4-1129298af1dd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6f474fa0-7112-4e4d-9d3c-4f3c30abc455</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nhập Hàng/TimKiem/Func_NH06- Tìm kiếm theo trạng thái Hủy</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e49116e-77e5-4d0f-9406-444e4dae7d86</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ead8a63a-85c9-4fec-81d1-9486cd93640e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>00162f71-56bb-4904-9de3-076c53cf7f14</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nhập Hàng/TimKiem/Func_NH07- Tìm kiếm theo trạng thái Đang xử lý</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>195dac77-acfd-4cfd-8f74-4d45ba3b502f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7b886bcc-f995-4628-9761-de5723cd4356</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bb9de2ba-88eb-41fe-9960-f18000dbb5c8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nhập Hàng/TimKiem/Func_NH08- Tìm kiếm theo thời gian Hôm nay</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>e04b2fcf-a0b1-4443-9f74-b815e4072f13</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nhập Hàng/TimKiem/Func_NH09- Tìm kiếm theo Thời gian Tháng này</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>63c65bc2-6ecf-4231-accc-f7f990a49da2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Nhập Hàng/TimKiem/Func_NH10- Tìm kiếm theo thời gian Tháng trước</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
