<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>HangHoa_ThemHangHoa</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>19f97562-4ad4-4550-ab5b-fa03010ed4cc</testSuiteGuid>
   <testCaseLink>
      <guid>d0255a94-10b6-42ed-a810-40f08feb542c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Quản lý hàng hóa/ThemMoi/Func_HH42-Thêm mới sản phẩm thành công</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db4e549c-6182-4a30-a6f1-ababfce61856</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b76e2fd1-58b2-4010-ac2d-d5ecd09e9aab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c9f4050f-37b9-4b71-ad1f-96d0e7d01fc7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba127cea-25fe-4274-927a-9cb52f3b07c0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c08d009b-59e5-45a4-84ec-6bef13044aa8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>788484c3-9069-4712-a937-44fe48ebb6fc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Quản lý hàng hóa/ThemMoi/Func_HH43- Thêm mới sp với loại Dịch vụ</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>e25461ec-7a84-43fb-af6b-b1600ba6d2ae</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Quản lý hàng hóa/ThemMoi/Func_HH44- Thêm mới sp với loại Hàng hóa</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>e38d0785-6c8f-4ae1-a0b7-877760de1f2c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Quản lý hàng hóa/ThemMoi/Func_HH45- Thêm mới sp với loại Combo</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>98b5766f-d868-4d52-8502-4a93debc4a15</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Quản lý hàng hóa/ThemMoi/Func_HH46---Func_HH49-Thêm mới sản phẩm với các nhóm hàng</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>ce6ba3f1-a9df-40cc-bab1-027d6eb7d3bc</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Product/NhomLoaiHang</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f8a15b15-0483-45f6-85ea-c0acf66e88a4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ce6ba3f1-a9df-40cc-bab1-027d6eb7d3bc</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Nhóm</value>
         <variableId>c429e8c5-01a9-4887-be08-cff608a2c846</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0451e723-d26a-49df-a358-a942812e4cdb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Quản lý hàng hóa/ThemMoi/Func_HH50- Thêm mới sản phẩm với hình ảnh</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf4fd8db-eacb-4d31-b2aa-499f37364dca</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2a3a3c2b-5b94-4f2e-8946-53afee7acf90</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Quản lý hàng hóa/ThemMoi/Func_HH51- Kiểm tra tự sinh mã hàng</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d64347f4-dbcc-40c3-9abc-968253368609</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>029c77fd-d242-48bf-9b12-78821054a2e2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>00bd8229-7516-4792-926e-7d8c290ae9b4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>999c9acc-530d-4eca-b020-7db056f6510a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b50e9b86-94ff-456b-8625-1c5fe52b6964</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8bd75475-8827-43bb-be9f-16b9a985a949</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c9cef094-4aab-413d-8943-99d0d51edc48</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Quản lý hàng hóa/ThemMoi/Func_HH52_Kiểm tra bỏ trống trường bắt buộc</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>87c72a68-e00a-4b28-b24b-4bb7acfccd94</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b38b854b-3aa9-48cf-9551-4d6883672cfb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>67cc6f0a-db35-44cd-985a-27929d2b65ff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ccf84d8a-de6e-4758-9c81-3dfa810fa8c6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aeac1166-dd34-41e4-8b07-95d5329f788e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3608398c-be73-4032-b460-856f32b03249</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fd76d837-d665-4efb-8762-4f260166fe82</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Quản lý hàng hóa/ThemMoi/Func_HH54--59- Kiểm tra không điền đầy đủ thông tin</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>f24c65f1-7b92-40f2-b1ab-782398a89db3</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Product/BoTrongCacTruong</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1147060b-13c8-4892-9d5f-4e48c1496c0a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f24c65f1-7b92-40f2-b1ab-782398a89db3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>giaBan</value>
         <variableId>5207376f-4d7e-47fc-a54b-3742ddd2befb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f24c65f1-7b92-40f2-b1ab-782398a89db3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>giaVon</value>
         <variableId>76136b9d-b26c-4497-8d95-db35c196ae12</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f24c65f1-7b92-40f2-b1ab-782398a89db3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>tonKho</value>
         <variableId>0c977b40-4eb4-420c-893a-6f2c4b633167</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f24c65f1-7b92-40f2-b1ab-782398a89db3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>dvt</value>
         <variableId>98465b47-f1ae-4172-a113-db57a9436b5c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f24c65f1-7b92-40f2-b1ab-782398a89db3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>tc_id</value>
         <variableId>ce7d974d-a960-44fc-a76e-8b31e87b1f3c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d98e8178-b51d-4d6b-8caa-95657b81a134</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Quản lý hàng hóa/ThemMoi/Func_HH60--Kiểm tra khi click Thoát</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c107d77c-8685-4fe2-8139-cb52685fa5d9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>55a14abe-6b55-4827-bb6e-0bf8f310d088</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88d128cf-0504-4b08-bcb5-cee428474361</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ffbecc0-3a4b-42e2-9fd3-48225b69bd49</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>70c78448-d7df-402f-a425-d6f1b7fbbdc5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>246a61c2-4d3a-4dc4-a821-7d9ebd93fd25</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e3ca3c79-dfbd-42dd-aef7-b89bad7e65ab</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Quản lý hàng hóa/ThemMoi/Func_HH61-Kiểm tra thêm mới với button Lưu và Thêm Mới</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa4cc6b5-9328-4f63-a078-69ec16490ff5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ceb2a7b-b6e0-4644-8622-d6e96177bddc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7aba7aa5-5c46-4407-a9a2-d821e365c49b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0e45070-028a-4e2e-ac3b-2ff66b676238</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02c82fa9-c619-43a9-9917-1a0599e13f64</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1c71243b-bd93-4a44-b500-163150fc740e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f5ea40f2-5f3c-4e16-9911-84a2f5d0fd89</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>044abd30-c66a-4fa6-9b91-fac16691fca1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Quản lý hàng hóa/ThemMoi/Func_HH62-Kiểm tra thêm mới với button Lưu và Copy</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bdabeb22-e7cd-4089-aa8d-ba6a876f2b00</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1c25c601-8272-4ab5-bef4-443ae5b7b863</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c754ca7f-9d92-4132-b8a0-8c7c70ee303f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a87de7b-741f-4301-aa1c-a6b3d8b145f3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bcdd8597-cd2e-4b65-b05d-af9244a0788e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>696b4abd-402c-422d-b4ad-9eed930eb145</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>074b1a08-7598-44c3-bfd1-a60c1ce158e6</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
