<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>HangHoa_XoaHangHoa</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>81a596e8-4a43-4c02-9c01-73c061351b20</testSuiteGuid>
   <testCaseLink>
      <guid>b3d9fb89-85aa-4995-a6f3-6c127d442b0c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Quản lý hàng hóa/Xoa/Funtion/XoaVaAn_X</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c99dcaa9-6079-4bb2-9a52-43cc97a260f9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8c447aa3-2a14-4fc3-ac9a-ace8bb3bac2e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Quản lý hàng hóa/Xoa/Funtion/XoaVaThoat</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f07add66-5035-4fac-aa20-cc97f34b4547</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b080dcea-a994-40c6-8803-6e894ab5e81a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Quản lý hàng hóa/Xoa/Funtion/Xóa thành công</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6341daf6-9629-48a2-b272-0325f2b600e5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>520655e6-5f06-4230-9532-745a20b0a9dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>26390995-3388-47d5-b009-cc7eb58ec4c2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f7c7f8aa-bb7c-4565-9039-f8e7c5406b05</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1efd8b48-e0f5-409d-84ab-637d0e66a1b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2428df6e-1897-490c-9efc-a8b0f6cdb7bc</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
