analytics.onpremise.enable=true
analytics.integration.enable=true
analytics.project="{\\n  \\"id\\"\: 3452164,\\n  \\"name\\"\: \\"Sample - HR Web App \#3452164\\",\\n  \\"teamId\\"\: 3430005,\\n  \\"organizationId\\"\: 3481657,\\n  \\"isSampleProject\\"\: false,\\n  \\"canAutoIntegrate\\"\: false\\n}"
analytics.team="{\\n  \\"id\\"\: 3430005\\n}"
analytics.testcloud.integration.enable=false
analytics.testreport.autoupload.enable=true
analytics.testcloud.hub.switchHub.enable=false
onpremise.email="bamngouia@gmail.com"
onpremise.password="vocouS53JYOrHcEo7gJpoQ\=\="
analytics.onpremise.organization="{\\"accountId\\"\:1669649,\\"accountUuid\\"\:\\"4952057c-4b99-4dc7-a8ae-cffe3ff1c832\\",\\"id\\"\:3481657,\\"name\\"\:\\"My Organization_01\\",\\"role\\"\:\\"OWNER\\",\\"samlSSO\\"\:false,\\"kreLicense\\"\:false,\\"strictDomain\\"\:false}"
analytics.onpremise.server="https\://testops.katalon.io"
